const AWARDS = [
  '2026年入展「笔底清风.汕头市青年扇面书法小品网络展」',
  '第二届「艺蕴中国」艺术教育创新成果展暨新时代学校美育浸润行动成果展 · 金奖',
  '2023年「国青杯」全国高校艺术设计作品展 · 二等奖',
  '第九届中国国际「互联网+」大学生创新创业大赛 · 省级铜奖',
  '「筑梦扬帆正青春」深圳、珠海、香港、澳门四地大学生优秀书法联展 · 三等奖',
  '深圳大学艺术学部「学习二十大，我想说」书法作品 · 入围奖',
  '深圳大学校庆40周年「与古为徒」百幅教学临摹作品展 · 入选',
  '2021年第二届「艺术之星」全国书画大赛《我是党员》· 银奖',
  '2023年《高原女孩》参展「艺术的维度」深圳大学艺术作品交流展',
];

const WORKS = [
  {
    id: 'image1',
    title: '雪景寒林图',
    category: 'landscape',
    categoryLabel: '山水',
    year: '2023',
    size: '793.5 × 160.3 cm',
    medium: '山水画',
    image: 'assets/images/image1.jpeg',
    description: '山水作品，以寒林雪景展现传统山水意境与空间层次。',
  },
  {
    id: 'calligraphy-8',
    title: '唐诗词选',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2024',
    size: '46 × 217 cm',
    medium: '米芾行书',
    image: 'assets/images/image9.jpeg',
    images: ['assets/images/image9.jpeg', 'assets/images/image10.png'],
    description: '《唐诗选录》节选自唐朝诗词，以米芾行书创作，采用横幅拼接形式展现「八面出锋」的艺术特色。指导老师：赵辉老师',
  },
  {
    id: 'image12',
    title: '东坡题跋',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2024',
    size: '75 × 139 cm',
    medium: '褚遂良楷体',
    image: 'assets/images/image12.png',
    description: '作品内容选自《东坡题跋》，学习褚遂良楷体，以中楷形式展示；采用方块拼贴，仿古洒金纸做底，展现褚遂良艺术特色。指导老师：赵辉老师',
  },
  {
    id: 'image13',
    title: '蜀素帖（临·局部一）',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2022',
    size: '29.7 × 240 cm',
    medium: '行书',
    image: 'assets/images/image13.jpeg',
    description: '临《蜀素帖》局部。初时只仿其欹侧之形，近来渐悟米芾「刷字」不独是快，更在随势调锋。',
  },
  {
    id: 'image14',
    title: '蜀素帖（临·局部二）',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2022',
    size: '29.7 × 240 cm',
    medium: '行书',
    image: 'assets/images/image14.jpeg',
    description: '临《蜀素帖》局部。每遇转折处刻意放缓，学他笔锋暗换，墨痕里藏着真性情。',
  },
  {
    id: 'image15',
    title: '毛主席词选',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2023',
    size: '69 × 138 cm',
    medium: '米芾行书',
    image: 'assets/images/image15.png',
    description: '以米芾行书笔意临创《毛主席词选》。八面出锋、沉着痛快，力求以经典之法写时代语。',
  },
  {
    id: 'image16',
    title: '习近平主席语录节选',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2023',
    size: '69 × 138 cm',
    medium: '米芾行书',
    image: 'assets/images/image16.png',
    description: '以米芾行书笔意临创《习近平主席语录节选》。获深圳大学艺术学部「学习二十大，我想说」入围奖。',
  },
  {
    id: 'image17',
    title: '临书谱节选（草书）',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2023',
    size: '四尺四裁',
    medium: '草书',
    image: 'assets/images/image17.jpeg',
    description: '《书谱》节选草书局部。细究笔锋往来，才懂孙过庭「草以点画为情性，使转为形质」。',
  },
  {
    id: 'image18',
    title: '集吴昌硕石鼓文（隶书）',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2023',
    size: '四尺三裁',
    medium: '隶书',
    image: 'assets/images/image18.jpeg',
    description: '集对联：置酒张灯促华馔，天麀鸣囿乐康平。',
  },
  {
    id: 'image19',
    title: '石州引',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2023',
    size: '四尺斗方',
    medium: '草书',
    image: 'assets/images/image19.jpeg',
    description: '集贺铸《石州引》，笔随词情起伏，笔墨间尽抒离愁婉转之韵。',
  },
  {
    id: 'image20',
    title: '错落珊瑚珠',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '30 × 40 cm',
    medium: '写意',
    image: 'assets/images/image20.png',
    description: '临吴昌硕《错落珊瑚珠》画幅中央画两株天竹，右株墨色浓，叶繁，左株赭色浅，叶稀，相映成趣，错落有致。',
  },
  {
    id: 'image21',
    title: '没骨花鸟习作',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '30 × 40 cm',
    medium: '没骨画',
    image: 'assets/images/image21.jpeg',
    description: '花鸟没骨画练习，以晕染代替勾勒，传达生命意趣。',
  },
  {
    id: 'image22',
    title: '红梅图',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '30 × 40 cm',
    medium: '写意',
    image: 'assets/images/image22.png',
    description: '临吴昌硕《红梅图》。',
  },
  {
    id: 'image23',
    title: '吴昌硕花卉条屏',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '30 × 40 cm',
    medium: '写意',
    image: 'assets/images/image23.png',
    description: '临吴昌硕花卉四条屏之一，从菊石里练习用笔轻重徐疾。',
  },
  {
    id: 'image24',
    title: '红花春趣',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '30 × 40 cm',
    medium: '没骨画',
    image: 'assets/images/image24.jpeg',
    description: '创作小品（2023）没骨画系列。师法自然，在临摹古画中体悟前人笔墨韵致。',
  },
  {
    id: 'image25',
    title: '花风蝶',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '30 × 40 cm',
    medium: '没骨画',
    image: 'assets/images/image25.png',
    description: '没骨画系列创作小品，作品以没骨绘菊，蝶舞繁花，意在表达春日悠然景致。',
  },
  {
    id: 'image26',
    title: '荔枝',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '30 × 40 cm',
    medium: '没骨画',
    image: 'assets/images/image26.png',
    description: '临摹荔枝小品，悟没骨设色，品硕果温润意趣。',
  },
  {
    id: 'image27',
    title: '玉兰黄鹂',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2025',
    size: '50 × 60 cm',
    medium: '没骨画',
    image: 'assets/images/image27.jpeg',
    description: '花鸟小品（2025）。研习花鸟国画，以「师法自然」为核心。',
  },
  {
    id: 'image28',
    title: '墨虾',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2025',
    size: '30 × 40 cm',
    medium: '写意',
    image: 'assets/images/image28.jpeg',
    description: '画齐白石的虾不只是对物象的简单再现，更要传达生命的意趣。',
  },
  {
    id: 'image29',
    title: '花期有约',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '66 × 133 cm',
    medium: '没骨画',
    image: 'assets/images/image29.png',
    description: '没骨画《花期有约》，以烂漫姿态铺展，鲜活又朦胧，尽显花木热烈蓬勃。',
  },
  {
    id: 'image30',
    title: '岭南风格',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2024',
    size: '33.5 × 133 cm',
    medium: '没骨画',
    image: 'assets/images/image30.jpg',
    description: '三角梅以烂漫姿态铺展，没骨技法让花瓣粉紫如晕染开的梦；喜鹊振翅于粉调天际，传递对生活满含希望与喜悦的期许。',
  },
  {
    id: 'image32',
    title: '沈周《仿大痴山水图》（临·全幅）',
    category: 'landscape',
    categoryLabel: '山水',
    year: '2025',
    size: '115.5 × 48.5 cm',
    medium: '山水画',
    image: 'assets/images/image32.jpg',
    description: '沈周《仿大痴山水图》临摹全幅。画面气韵安宁，尽显「以山水寄心」的境界，学古学典终究是为找到自己的笔墨。',
  },
  {
    id: 'image33',
    title: '高原女孩',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '69 × 138 cm',
    medium: '中国画',
    image: 'assets/images/image33.jpeg',
    description: '人物作品《高原女孩》。2023年参展「艺术的维度——深圳大学艺术作品交流展」。',
  },
  {
    id: 'image34',
    title: '油画同学',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '69 × 138 cm',
    medium: '白描',
    image: 'assets/images/image34.png',
    description: '人物写生作品《油画同学》，用白描捕捉同学肖像与神态。',
  },
  {
    id: 'image35',
    title: '永乐宫壁画人物（白描）',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '69 × 138 cm',
    medium: '白描',
    image: 'assets/images/image35.png',
    description: '白描作品《永乐宫壁画人物》，以线条表现壁画人物神韵与衣纹结构。',
  },
  {
    id: 'figure-32',
    title: '神骏图（临）',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '87 × 37 cm',
    medium: '人物绢本',
    image: 'assets/images/image36.jpeg',
    images: ['assets/images/image36.jpeg', 'assets/images/image37.jpeg'],
    description: '临摹（五代十国）佚名《神骏图》。人物线条流畅，衣袂飘飘似有动感；设色古朴雅致，将人物神态与画面氛围精准传达。指导老师：孔蓓',
  },
  {
    id: 'image38',
    title: '写意人物（一）',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '69 × 138 cm',
    medium: '写意人物',
    image: 'assets/images/image38.jpeg',
    description: '写意人物临摹，以笔墨表现人物神韵与动态。',
  },
  {
    id: 'image39',
    title: '写意人物（二）',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '—',
    medium: '写意人物',
    image: 'assets/images/image39.jpeg',
    description: '写意人物系列，注重神态捕捉与笔墨节奏。',
  },
  {
    id: 'image40',
    title: '写意人物（三）',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '—',
    medium: '写意人物',
    image: 'assets/images/image40.jpeg',
    description: '写意人物系列，以简练笔墨传达人物性格与情境。',
  },
  {
    id: 'image41',
    title: '写意人物（四）',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '—',
    medium: '写意人物',
    image: 'assets/images/image41.png',
    description: '写意人物系列，探索人物与留白的互动关系。',
  },
  {
    id: 'image42',
    title: '写生的一角',
    category: 'sketch',
    categoryLabel: '素描',
    year: '2021',
    size: '106 × 76 cm',
    medium: '素描',
    image: 'assets/images/image42.jpeg',
    description: '素描作品《写生的一角》，观察光影、结构与空间关系的练习。',
  },
  {
    id: 'image43',
    title: '油画作品（一）',
    category: 'oil',
    categoryLabel: '油画',
    year: '2021',
    size: '30 × 40 cm',
    medium: '油画',
    image: 'assets/images/image43.jpeg',
    description: '油画创作系列，探索色彩、造型与光影的表达。',
  },
  {
    id: 'image44',
    title: '油画作品（二）',
    category: 'oil',
    categoryLabel: '油画',
    year: '2021',
    size: '30 × 40 cm',
    medium: '油画',
    image: 'assets/images/image44.jpeg',
    description: '油画创作系列，练习色调归纳与画面构成。',
  },
  {
    id: 'image45',
    title: '油画作品（三）',
    category: 'oil',
    categoryLabel: '油画',
    year: '2021',
    size: '30 × 40 cm',
    medium: '油画',
    image: 'assets/images/image45.jpeg',
    description: '油画创作系列，表现物体质感与空间深度。',
  },
  {
    id: 'image46',
    title: '油画作品（四）',
    category: 'oil',
    categoryLabel: '油画',
    year: '2021',
    size: '30 × 40 cm',
    medium: '油画',
    image: 'assets/images/image46.jpeg',
    description: '油画创作系列，探索笔触与色彩的结合。',
  },
  {
    id: 'image47',
    title: '油画作品（五）',
    category: 'oil',
    categoryLabel: '油画',
    year: '2021',
    size: '30 × 40 cm',
    medium: '油画',
    image: 'assets/images/image47.jpeg',
    description: '油画创作系列。',
  },
  {
    id: 'image48',
    title: '油画作品（六）',
    category: 'oil',
    categoryLabel: '油画',
    year: '2021',
    size: '30 × 40 cm',
    medium: '油画',
    image: 'assets/images/image48.jpeg',
    description: '油画创作系列。',
  },
  {
    id: 'image49',
    title: '油画作品（七）',
    category: 'oil',
    categoryLabel: '油画',
    year: '2021',
    size: '30 × 40 cm',
    medium: '油画',
    image: 'assets/images/image49.jpeg',
    description: '油画创作系列。',
  },
  {
    id: 'image50',
    title: '版画作品（一）',
    category: 'print',
    categoryLabel: '版画',
    year: '2022',
    size: 'A4',
    medium: '版画',
    image: 'assets/images/image50.png',
    description: '版画创作系列，以刀味与印痕传递艺术语言。',
  },
  {
    id: 'image51',
    title: '版画作品（二）',
    category: 'print',
    categoryLabel: '版画',
    year: '2022',
    size: 'A4',
    medium: '版画',
    image: 'assets/images/image51.png',
    description: '版画创作系列，探索黑白对比与线条韵律。',
  },
  {
    id: 'image52',
    title: '版画作品（三）',
    category: 'print',
    categoryLabel: '版画',
    year: '2022',
    size: 'A4',
    medium: '版画',
    image: 'assets/images/image52.jpeg',
    description: '版画创作系列，练习刻刀语言与画面构成。',
  },
  {
    id: 'image53',
    title: '版画作品（四）',
    category: 'print',
    categoryLabel: '版画',
    year: '2022',
    size: 'A4',
    medium: '版画',
    image: 'assets/images/image53.png',
    description: '版画创作系列。',
  },
  {
    id: 'image54',
    title: '版画作品（五）',
    category: 'print',
    categoryLabel: '版画',
    year: '2022',
    size: 'A4',
    medium: '版画',
    image: 'assets/images/image54.png',
    description: '版画创作系列。',
  },
  {
    id: 'image55',
    title: '版画作品（六）',
    category: 'print',
    categoryLabel: '版画',
    year: '2022',
    size: 'A4',
    medium: '版画',
    image: 'assets/images/image55.png',
    description: '版画创作系列。',
  },
  {
    id: 'sculpture-51',
    title: '雕塑作品（一）',
    category: 'sculpture',
    categoryLabel: '雕塑',
    year: '2022',
    size: '—',
    medium: '雕塑',
    image: 'assets/images/image56.jpeg',
    images: ['assets/images/image56.jpeg', 'assets/images/image57.jpeg', 'assets/images/image58.jpeg'],
    description: '雕塑创作系列，从立体空间理解形态、体量与结构；练习体积感与空间关系；探索材料与造型的表达。',
  },
  {
    id: 'sculpture-52',
    title: '雕塑作品（二）',
    category: 'sculpture',
    categoryLabel: '雕塑',
    year: '2022',
    size: '—',
    medium: '雕塑',
    image: 'assets/images/image59.jpeg',
    images: ['assets/images/image59.jpeg', 'assets/images/image60.jpeg', 'assets/images/image61.jpeg', 'assets/images/image62.jpeg'],
    description: '雕塑创作系列。',
  },
  {
    id: 'image63',
    title: '奶奶家的柿子',
    category: 'watercolor',
    categoryLabel: '水彩',
    year: '2020',
    size: '39 × 54 cm',
    medium: '水彩',
    image: 'assets/images/image63.jpeg',
    description: '水彩作品《奶奶家的柿子》，以透明水彩捕捉生活中温暖细腻的瞬间。',
  },
  {
    id: 'image64',
    title: '东山岛上的房子',
    category: 'watercolor',
    categoryLabel: '水彩',
    year: '2021',
    size: '19 × 27 cm',
    medium: '水彩',
    image: 'assets/images/image64.jpeg',
    description: '水彩作品《东山岛上的房子》，记录东山岛的建筑与地域氛围。',
  },
  {
    id: 'image65',
    title: '大学课堂的写生静物',
    category: 'watercolor',
    categoryLabel: '水彩',
    year: '2021',
    size: '39 × 45 cm',
    medium: '水彩',
    image: 'assets/images/image65.jpeg',
    description: '水彩作品《大学课堂的写生静物》，练习观察、构图与色彩控制。',
  },
  {
    id: 'image66',
    title: '敦煌壁画书籍排版',
    category: 'design',
    categoryLabel: '设计',
    year: '2021',
    size: '',
    medium: '版式设计 · CDR',
    image: 'assets/images/image66.jpeg',
    description: '以敦煌壁画为历史背景，制作关于敦煌壁画的书籍排版效果图。',
  },
  {
    id: 'image67',
    title: '书籍版式设计',
    category: 'design',
    categoryLabel: '设计',
    year: '2021',
    size: '',
    medium: '版式设计 · CDR',
    image: 'assets/images/image67.jpeg',
    description: '版式设计练习，CDR 软件制作。',
  },
  {
    id: 'design-58',
    title: '日落计划 · 音乐会海报',
    category: 'design',
    categoryLabel: '设计',
    year: '2024',
    size: '—',
    medium: '海报设计 · CDR',
    image: 'assets/images/image68.jpeg',
    images: ['assets/images/image68.jpeg', 'assets/images/image69.jpeg'],
    description: '以「日落计划」为名的音乐会海报设计，寓意青春应去追寻梦想。',
  },
  {
    id: 'design-59',
    title: 'LOGO 设计',
    category: 'design',
    categoryLabel: '设计',
    year: '2021',
    size: '—',
    medium: 'LOGO · CDR',
    image: 'assets/images/image70.jpeg',
    images: ['assets/images/image70.jpeg', 'assets/images/image71.jpeg'],
    description: 'LOGO 设计作品，探索图形语言与视觉识别。',
  },
  {
    id: 'image72',
    title: 'IP 形象设计（一）',
    category: 'design',
    categoryLabel: '设计',
    year: '2023',
    size: '—',
    medium: 'IP · LOGO · 排版',
    image: 'assets/images/image72.png',
    description: '互联网+项目 IP 形象设计、LOGO 及排版设计。',
  },
  {
    id: 'image76',
    title: 'IP 形象设计（二）',
    category: 'design',
    categoryLabel: '设计',
    year: '2023',
    size: '—',
    medium: 'IP · LOGO · 排版',
    image: 'assets/images/image76.png',
    description: '互联网+项目团队相关视觉设计。',
  },
  {
    id: 'image73',
    title: '华商律所文创设计',
    category: 'design',
    categoryLabel: '设计',
    year: '2023',
    size: '—',
    medium: 'IP · LOGO · 排版',
    image: 'assets/images/image73.png',
    description: 'IP 形象与品牌视觉设计。',
  },
  {
    id: 'design-63',
    title: '华商律所logo',
    category: 'design',
    categoryLabel: '设计',
    year: '2023',
    size: '—',
    medium: 'LOGO · procreate',
    image: 'assets/images/image74.png',
    images: ['assets/images/image74.png', 'assets/images/image75.png'],
    description: '华商律所 LOGO 设计方案。',
  },
  {
    id: 'image77',
    title: '互联网+项目团队合照',
    category: 'design',
    categoryLabel: '设计',
    year: '2023',
    size: '—',
    medium: '摄影 · 设计',
    image: 'assets/images/image77.jpeg',
    description: '互联网+项目团队合照，记录项目合作与创作过程。',
  }
];
