const AWARDS = [
  '第二届「艺蕴中国」艺术教育创新成果展暨新时代学校美育浸润行动成果展 · 金奖',
  '2023年「国青杯」全国高校艺术设计作品展 · 二等奖',
  '第九届中国国际「互联网+」大学生创新创业大赛 · 省级铜奖',
  '「筑梦扬帆正青春」深圳、珠海、香港、澳门四地大学生优秀书法联展 · 三等奖',
  '深圳大学艺术学部「学习二十大，我想说」书法作品 · 入围奖',
  '深圳大学校庆40周年「与古为徒」百幅教学临摹作品展 · 入选',
  '2021年第二届「艺术之星」全国书画大赛《我是党员》· 银奖',
  '2023年《高原女孩》参展「艺术的维度」深圳大学艺术作品交流展',
];

const WORKS = [
  {
    id: 'tang-poems',
    title: '唐诗词选',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2024',
    size: '46 × 217 cm',
    medium: '米芾行书',
    image: 'assets/images/image10.png',
    description: '节选自唐朝诗词，以米芾行书创作，采用横幅拼接形式展现「八面出锋」的艺术特色。指导老师：赵辉老师',
  },
  {
    id: 'dongpo',
    title: '东坡题跋',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2024',
    size: '75 × 139 cm',
    medium: '褚遂良楷体',
    image: 'assets/images/image12.png',
    description: '学习褚遂良楷体，以中楷形式展示；采用方块拼贴，仿古洒金纸做底。指导老师：赵辉老师',
  },
  {
    id: 'shusu',
    title: '蜀素帖（临）',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2022',
    size: '29.7 × 240 cm',
    medium: '行书',
    image: 'assets/images/image14.jpeg',
    description: '临《蜀素帖》月余，渐悟米芾「刷字」不独是快，更在随势调锋，笔锋暗换里藏着真性情。',
  },
  {
    id: 'xjp-quote',
    title: '习近平主席语录节选',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2023',
    size: '69 × 138 cm',
    medium: '米芾行书',
    image: 'assets/images/image16.png',
    description: '以米芾行书笔意临创，八面出锋、沉着痛快，以经典之法写时代语。',
  },
  {
    id: 'mao-poems',
    title: '毛主席词选',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2023',
    size: '69 × 138 cm',
    medium: '米芾行书',
    image: 'assets/images/image15.png',
    description: '以米芾行书笔意临创，力求以经典之法写时代语。',
  },
  {
    id: 'shupu',
    title: '书谱节选',
    category: 'calligraphy',
    categoryLabel: '书法',
    year: '2023',
    size: '—',
    medium: '草书 · 篆书',
    image: 'assets/images/image18.jpeg',
    description: '初临《书谱》，细究笔锋往来，才懂孙过庭「草以点画为情性，使转为形质」。',
  },
  {
    id: 'flower-bird-1',
    title: '没骨花鸟',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '30 × 40 cm',
    medium: '没骨画',
    image: 'assets/images/image21.jpeg',
    description: '没骨技法，以晕染代替勾勒，传达花木生命的意趣。',
  },
  {
    id: 'creation-sketch',
    title: '创作小品',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '—',
    medium: '没骨画',
    image: 'assets/images/image25.png',
    description: '没骨画系列创作小品，师法自然，从线条与晕染中把握笔墨层次。',
  },
  {
    id: 'flower-bird-2025',
    title: '花鸟小品',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2025',
    size: '—',
    medium: '花鸟画',
    image: 'assets/images/image28.jpeg',
    description: '研习花鸟国画，以师法自然为核心，传达生命的意趣。',
  },
  {
    id: 'huaqi',
    title: '花期有约',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2023',
    size: '66 × 133 cm',
    medium: '没骨画',
    image: 'assets/images/image29.png',
    description: '没骨画作品，以烂漫姿态铺展，鲜活又朦胧，尽显花木的热烈蓬勃。',
  },
  {
    id: 'lingnan',
    title: '岭南风格',
    category: 'flower-bird',
    categoryLabel: '花鸟',
    year: '2024',
    size: '33.5 × 133 cm',
    medium: '没骨画',
    image: 'assets/images/image30.jpg',
    description: '三角梅以烂漫姿态铺展，没骨技法让花瓣的粉紫如晕染开的梦；喜鹊振翅于粉调天际，传递对生活满含希望与喜悦的期许。',
  },
  {
    id: 'snow-landscape',
    title: '雪景寒林图',
    category: 'landscape',
    categoryLabel: '山水',
    year: '2023',
    size: '793.5 × 160.3 cm',
    medium: '山水画',
    image: 'assets/images/image1.jpeg',
    description: '山水作品，以寒林雪景展现传统山水意境。',
  },
  {
    id: 'shen-zhou',
    title: '沈周《仿大痴山水图》（临）',
    category: 'landscape',
    categoryLabel: '山水',
    year: '2025',
    size: '115.5 × 48.5 cm',
    medium: '山水画',
    image: 'assets/images/image32.jpg',
    description: '学习沈周「师古而化」之妙，减繁密增松活，以山水寄心，寻己之笔墨。',
  },
  {
    id: 'plateau-girl',
    title: '高原女孩',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '69 × 138 cm',
    medium: '中国画',
    image: 'assets/images/image33.jpeg',
    description: '人物作品，2023年参展「艺术的维度」深圳大学艺术作品交流展。',
  },
  {
    id: 'oil-classmate',
    title: '油画同学',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '69 × 138 cm',
    medium: '油画',
    image: 'assets/images/image35.png',
    description: '人物写生作品，以油画媒介捕捉人物神态。',
  },
  {
    id: 'shenjun',
    title: '神骏图（临）',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '87 × 37 cm',
    medium: '人物绢本',
    image: 'assets/images/image37.jpeg',
    description: '临摹（五代十国）佚名《神骏图》，沉浸于古人笔墨韵味，体悟线条运用与设色技巧。指导老师：孔蓓',
  },
  {
    id: 'freehand-figure',
    title: '写意人物',
    category: 'figure',
    categoryLabel: '人物',
    year: '2023',
    size: '—',
    medium: '写意人物',
    image: 'assets/images/image39.jpeg',
    description: '写意人物创作，以笔墨表现人物神韵与意境。',
  },
  {
    id: 'sketch-corner',
    title: '写生的一角',
    category: 'sketch',
    categoryLabel: '素描',
    year: '2021',
    size: '106 × 76 cm',
    medium: '素描',
    image: 'assets/images/image42.jpeg',
    description: '素描写生作品，观察光影与结构的练习。',
  },
  {
    id: 'oil-1',
    title: '油画作品',
    category: 'oil',
    categoryLabel: '油画',
    year: '2021',
    size: '—',
    medium: '油画',
    image: 'assets/images/image44.jpeg',
    description: '油画创作，探索色彩与造型的表达。',
  },
  {
    id: 'print-1',
    title: '版画作品',
    category: 'print',
    categoryLabel: '版画',
    year: '2022',
    size: '—',
    medium: '版画',
    image: 'assets/images/image47.jpeg',
    description: '版画创作，以刀味与印痕传递艺术语言。',
  },
  {
    id: 'sculpture-1',
    title: '雕塑作品',
    category: 'sculpture',
    categoryLabel: '雕塑',
    year: '2022',
    size: '—',
    medium: '雕塑',
    image: 'assets/images/image56.jpeg',
    description: '雕塑创作，从立体空间理解形态与体量。',
  },
  {
    id: 'persimmon',
    title: '奶奶家的柿子',
    category: 'watercolor',
    categoryLabel: '水彩',
    year: '2020',
    size: '39 × 54 cm',
    medium: '水彩',
    image: 'assets/images/image63.jpeg',
    description: '水彩写生，以透明水彩捕捉生活里的温暖瞬间。',
  },
  {
    id: 'dongshan',
    title: '东山岛上的房子',
    category: 'watercolor',
    categoryLabel: '水彩',
    year: '2021',
    size: '19 × 27 cm',
    medium: '水彩',
    image: 'assets/images/image64.jpeg',
    description: '风景水彩写生，记录东山岛的建筑与氛围。',
  },
  {
    id: 'still-life',
    title: '大学课堂的写生静物',
    category: 'watercolor',
    categoryLabel: '水彩',
    year: '2021',
    size: '39 × 45 cm',
    medium: '水彩',
    image: 'assets/images/image65.jpeg',
    description: '课堂静物写生，练习观察与色彩控制。',
  },
  {
    id: 'dunhuang',
    title: '敦煌壁画书籍排版',
    category: 'design',
    categoryLabel: '设计',
    year: '2024',
    size: '—',
    medium: '版式设计 · CDR',
    image: 'assets/images/image66.jpeg',
    description: '以敦煌壁画为历史背景，制作书籍排版效果图。',
  },
  {
    id: 'poster',
    title: '日落计划 · 音乐会海报',
    category: 'design',
    categoryLabel: '设计',
    year: '2024',
    size: '—',
    medium: '海报设计 · CDR',
    image: 'assets/images/image69.jpeg',
    description: '以「日落计划」为名的音乐会海报设计，寓意青春应去追寻梦想。',
  },
  {
    id: 'logo',
    title: 'LOGO 设计',
    category: 'design',
    categoryLabel: '设计',
    year: '2024',
    size: '—',
    medium: 'LOGO · CDR',
    image: 'assets/images/image71.jpeg',
    description: '标志设计作品，探索图形语言与品牌识别。',
  },
  {
    id: 'ip-design',
    title: 'IP 形象设计',
    category: 'design',
    categoryLabel: '设计',
    year: '2024',
    size: '—',
    medium: 'IP · LOGO · 排版',
    image: 'assets/images/image73.png',
    description: '互联网+项目 IP 形象、LOGO 及排版设计。',
  },
];
